//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FontFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FontFactory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TTGlyph name=&quot;one&quot; xMin=&quot;228&quot; yMin=&quot;0&quot; xMax=&quot;724&quot; yMax=&quot;1466&quot;&gt;
        ///      &lt;contour&gt;
        ///        &lt;pt x=&quot;724&quot; y=&quot;0&quot; on=&quot;1&quot;/&gt;
        ///        &lt;pt x=&quot;560&quot; y=&quot;0&quot; on=&quot;1&quot;/&gt;
        ///        &lt;pt x=&quot;560&quot; y=&quot;1239&quot; on=&quot;1&quot;/&gt;
        ///        &lt;pt x=&quot;541&quot; y=&quot;1220&quot; on=&quot;0&quot;/&gt;
        ///        &lt;pt x=&quot;468&quot; y=&quot;1171&quot; on=&quot;0&quot;/&gt;
        ///        &lt;pt x=&quot;377&quot; y=&quot;1123&quot; on=&quot;0&quot;/&gt;
        ///        &lt;pt x=&quot;276&quot; y=&quot;1081&quot; on=&quot;0&quot;/&gt;
        ///        &lt;pt x=&quot;228&quot; y=&quot;1069&quot; on=&quot;1&quot;/&gt;
        ///        &lt;pt x=&quot;228&quot; y=&quot;1235&quot; on=&quot;1&quot;/&gt;
        ///        &lt;pt x=&quot;282&quot; y=&quot;1250&quot; on=&quot;0&quot;/&gt;
        ///        &lt;pt x=&quot;403&quot; y=&quot;1301&quot; on=&quot;0&quot;/&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
    }
}
